& $wsudo -T REG ADD $reg_system\ControlSet001\Services\DiagTrack /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\WinDefend /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\Spooler /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\ShellHWDetection /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\SecurityHealthService /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\edgeupdate /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\edgeupdatem /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\BcastDVRUserService /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\MapsBroker /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\RetailDemo /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\Sense /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\WerSvc /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\WdNisSvc /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\XblAuthManager /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\XblGameSave /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\xboxgip /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\XboxGipSvc /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\XboxNetApiSvc /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\wscsvc /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\DPS /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\RasMan /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\DusmSvc /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\lfsvc /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\NcbService /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\PimIndexMaintenanceSvc /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\DevicePickerUserSvc /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\DevicesFlowUserSvc /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\WdiServiceHost /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\WdiSystemHost /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\SstpSvc /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\SDRSVC /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\diagsvc /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\WdBoot /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\WdFilter /v Start /t REG_DWORD /d 4 /f
& $wsudo -T REG ADD $reg_system\ControlSet001\Services\WdNisDrv /v Start /t REG_DWORD /d 4 /f
